pipeline{
    agent any
    stages{
        stage('Static Analysis'){
            steps{
                echo 'Static Analysis'
            }
        }
        stage('Compile'){
            steps{
                sh 'javac HelloWorld.java .'
            }
        }
        stage('Run'){
            steps{
                sh 'java HelloWorld.java'
            }
        }
    }
}
